apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: foo-api
  namespace: dev
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: foo-api
  targetCPUUtilizationPercentage: 60